# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vendelo_development
  username: postgres
  password: Leandro2009*
  host: localhost
  port: 5432

test:
  <<: *default
  database: vendelo_test
  username: postgres
  password: Leandro2009*
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: vendelo_production
    username: vendelo
    password: <%= ENV["VENDELO_DATABASE_PASSWORD"] %>
    host: localhost
    port: 5432

  cache:
    <<: *primary_production
    database: vendelo_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: vendelo_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: vendelo_production_cable
    migrations_paths: db/cable_migrate
